FROM docker.io/alpine:3.20

RUN apk add --no-cache git bash

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/

RUN which git && which uv

RUN apk add --no-cache build-base cmake
RUN apk add --no-cache less

WORKDIR /nested-dvc-test
RUN git clone https://github.com/rayhagimoto/nested-dvc-test .
RUN git checkout dvc_exp/cool-example-1-seed-sweep
WORKDIR /nested-dvc-test/examples/cool-example-1
RUN uv venv --python 3.14
RUN uv pip install dvc
# RUN source .venv/bin/activate && dvc exp pull origin

CMD ["bash"]
